[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group }}
{% for commit in commits %}
- {% if commit.breaking %}**BREAKING** {% endif %}{{ commit.message }} ([`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/khchehab/gospotify/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""

[git]
tag_pattern = "v[0-9].*"
conventional_commits = true
filter_unconventional = false

commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^docs?", group = "Documentation" },
  { message = "^test", group = "Testing" },
  { message = "^(chore|ci|build)", group = "Maintenance" },
  { message = ".*", group = "Other" },
]
